#!/bin/sh

FILES=$(git diff-tree --no-commit-id --name-only HEAD)
source venv/Scripts/activate

for File in FILES; do
    echo $File
    if [[ "$File" == *".py" ]]; then
        $(black ${File})
    fi
done